version: "3"
services:
    web:
        build: ./web/
        ports:
            - "8080:80"
        depends_on:
            - phpfpm
        volumes:
            - ./data/html:/html
    phpfpm:
        build: ./phpfpm/
        depends_on:
            - db
        volumes:
            - ./data/html:/html
    db:
        image: postgres:13
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres1234
        volumes:
            - ./data/postgres:/var/lib/postgresql/data